ssonar.projectKey=sachin-apache
sonar.projectName=Sachin APACHE Application
sonar.projectVersion=1.0

sonar.sources=code,apache

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/*.tgz,**/charts/**,**/.git/**